// Generated by stealth's scripts/export-ui.mjs.
export const categories = [
  {
    "key": "actions",
    "title": "Actions",
    "blurb": "Buttons that acknowledge the press and report what happened."
  },
  {
    "key": "inputs",
    "title": "Text inputs",
    "blurb": "Fields for typing, with every state accounted for."
  },
  {
    "key": "selection",
    "title": "Selection",
    "blurb": "Checks, radios, switches and chips that feel physical."
  },
  {
    "key": "sliders",
    "title": "Sliders & dials",
    "blurb": "Continuous values, dragged, stepped and scrubbed."
  },
  {
    "key": "pickers",
    "title": "Pickers",
    "blurb": "Choosing one or many from a list that can get long."
  },
  {
    "key": "dates",
    "title": "Dates & time",
    "blurb": "Calendars, fields and clocks that read like the locale."
  },
  {
    "key": "scheduling",
    "title": "Scheduling",
    "blurb": "Calendars full of events, slots and availability."
  },
  {
    "key": "forms",
    "title": "Forms",
    "blurb": "Validation, uploads and saving without losing work."
  },
  {
    "key": "async",
    "title": "Loading & progress",
    "blurb": "What the screen does while it waits, and when it fails."
  },
  {
    "key": "notifications",
    "title": "Notifications",
    "blurb": "Telling people something changed without shouting."
  },
  {
    "key": "dialogs",
    "title": "Dialogs & sheets",
    "blurb": "Surfaces that open over the page and give focus back."
  },
  {
    "key": "menus",
    "title": "Menus & tooltips",
    "blurb": "Actions tucked behind a trigger, found in one move."
  },
  {
    "key": "command",
    "title": "Command & search",
    "blurb": "Keyboard-first finding, filtering and jumping."
  },
  {
    "key": "navigation",
    "title": "Page navigation",
    "blurb": "Moving through the parts of one page or flow."
  },
  {
    "key": "app-nav",
    "title": "App navigation",
    "blurb": "Shells, sidebars and switchers that frame a product."
  },
  {
    "key": "disclosure",
    "title": "Disclosure",
    "blurb": "Showing more on request, and putting it back."
  },
  {
    "key": "scroll",
    "title": "Scroll",
    "blurb": "Headers, progress and reveals tied to the scroll position."
  },
  {
    "key": "tables",
    "title": "Tables",
    "blurb": "Dense rows people sort, select, edit and act on."
  },
  {
    "key": "data",
    "title": "Numbers & charts",
    "blurb": "Values that change, and the shape of them over time."
  },
  {
    "key": "display",
    "title": "Identity & display",
    "blurb": "Avatars, badges, tags and the small labels around them."
  },
  {
    "key": "media",
    "title": "Media",
    "blurb": "Images, video and audio, loaded and handled with care."
  },
  {
    "key": "content",
    "title": "Text & content",
    "blurb": "Type that arrives, changes and truncates gracefully."
  },
  {
    "key": "gestures",
    "title": "Gestures & drag",
    "blurb": "Things you pick up, throw, swipe and drop."
  },
  {
    "key": "collaboration",
    "title": "Collaboration",
    "blurb": "Other people in the same place, at the same time."
  },
  {
    "key": "messaging",
    "title": "Messaging",
    "blurb": "Threads, composers and receipts for conversations."
  },
  {
    "key": "ai-chat",
    "title": "AI conversation",
    "blurb": "Prompting, streaming and steering a model's reply."
  },
  {
    "key": "ai-agents",
    "title": "AI agents",
    "blurb": "Tools, plans, approvals and runs you can watch."
  },
  {
    "key": "commerce",
    "title": "Commerce & billing",
    "blurb": "Plans, carts and checkout that never surprise."
  },
  {
    "key": "onboarding",
    "title": "Auth & onboarding",
    "blurb": "Signing in, setting up and the first five minutes."
  },
  {
    "key": "settings",
    "title": "Settings",
    "blurb": "Preferences, keys and the dangerous buttons."
  },
  {
    "key": "developer",
    "title": "Developer",
    "blurb": "Code, logs, diffs and status for technical products."
  },
  {
    "key": "marketing",
    "title": "Marketing",
    "blurb": "The few pieces every product page needs."
  },
  {
    "key": "motion",
    "title": "Motion primitives",
    "blurb": "The small motion building blocks the rest are made of."
  }
];

export type Entry = { slug: string; name: string; category: string; description: string };
export const entries: Entry[] = [
  {
    "slug": "async-button",
    "name": "Async Button",
    "category": "actions",
    "description": "Tracks the promise it starts: busy, tick or retry, without ever changing width"
  },
  {
    "slug": "button",
    "name": "Button",
    "category": "actions",
    "description": "Four variants, three sizes, and a loading state that never changes width"
  },
  {
    "slug": "button-group",
    "name": "Button Group",
    "category": "actions",
    "description": "Attached buttons with hairlines between and one hover wash that glides"
  },
  {
    "slug": "copy-button",
    "name": "Copy Button",
    "category": "actions",
    "description": "Copies on press, draws a tick, holds its width and reverts on its own"
  },
  {
    "slug": "hold-to-confirm",
    "name": "Hold to Confirm",
    "category": "actions",
    "description": "Press and hold to commit; the label flips color under the filling edge"
  },
  {
    "slug": "icon-button",
    "name": "Icon Button",
    "category": "actions",
    "description": "Square button with a required label, warm tooltips and a sprung squash"
  },
  {
    "slug": "like-button",
    "name": "Like Button",
    "category": "actions",
    "description": "Optimistic like with a squash-and-stretch heart, rolling count and honest rollback"
  },
  {
    "slug": "speed-dial",
    "name": "Speed Dial",
    "category": "actions",
    "description": "A floating button that fans out labeled actions, nearest first, on a spring"
  },
  {
    "slug": "split-button",
    "name": "Split Button",
    "category": "actions",
    "description": "Main action plus a chevron menu; the choice can become the main action"
  },
  {
    "slug": "toggle-button",
    "name": "Toggle Button",
    "category": "actions",
    "description": "Stays on with aria-pressed, and its icon morphs: fills, pins, mutes"
  },
  {
    "slug": "toggle-group",
    "name": "Toggle Group",
    "category": "actions",
    "description": "Single or multiple toggles; one wash slides, neighboring washes join"
  },
  {
    "slug": "two-step-confirm",
    "name": "Two-step Confirm",
    "category": "actions",
    "description": "Asks once in place, springs to fit the question, then quietly takes it back"
  },
  {
    "slug": "floating-label",
    "name": "Floating Label Field",
    "category": "inputs",
    "description": "Label rests inside as the placeholder and floats up on focus, value or autofill"
  },
  {
    "slug": "inline-edit",
    "name": "Inline Edit",
    "category": "inputs",
    "description": "Text that becomes an input in place, saves optimistically, then draws a tick"
  },
  {
    "slug": "input",
    "name": "Input",
    "category": "inputs",
    "description": "Text field with prefix and suffix slots, a clear that fades in, and Field-aware invalid state"
  },
  {
    "slug": "masked-input",
    "name": "Masked Input",
    "category": "inputs",
    "description": "Formats cards, phones, dates and money as you type, caret held in place"
  },
  {
    "slug": "mention-input",
    "name": "Mention Input",
    "category": "inputs",
    "description": "A textarea where @ suggests people at the caret and names become tokens"
  },
  {
    "slug": "number-field",
    "name": "Number Field",
    "category": "inputs",
    "description": "Steppers you can hold, a label you can drag, digits that roll into place"
  },
  {
    "slug": "otp-field",
    "name": "OTP Field",
    "category": "inputs",
    "description": "Six cells that take paste and autofill, ripple while checking, clear on failure"
  },
  {
    "slug": "password-field",
    "name": "Password Field",
    "category": "inputs",
    "description": "Reveals with an eye that slashes itself, keeps the caret, warns on Caps Lock"
  },
  {
    "slug": "password-strength",
    "name": "Password Strength",
    "category": "inputs",
    "description": "Four bars that fill in order, a checklist that ticks, a settled announcement"
  },
  {
    "slug": "search-field",
    "name": "Search Field",
    "category": "inputs",
    "description": "Search box whose shortcut hint turns into a clear, with a patient spinner"
  },
  {
    "slug": "tag-input",
    "name": "Tag Input",
    "category": "inputs",
    "description": "Chips from Enter, comma or paste; duplicates flash the one already there"
  },
  {
    "slug": "textarea",
    "name": "Textarea",
    "category": "inputs",
    "description": "Grows with its text between row limits, counts near the limit, sends on ⌘↵"
  },
  {
    "slug": "checkbox",
    "name": "Checkbox",
    "category": "selection",
    "description": "Draws its tick, bends it into a dash when mixed, squashes on press"
  },
  {
    "slug": "checkbox-card",
    "name": "Checkbox Card",
    "category": "selection",
    "description": "Selectable cards whose corner check pops in, with a select-all that counts"
  },
  {
    "slug": "checklist",
    "name": "Checklist",
    "category": "selection",
    "description": "Tasks that strike through, then glide into Completed, with a rolling count"
  },
  {
    "slug": "choice-chips",
    "name": "Choice Chips",
    "category": "selection",
    "description": "Filter chips whose check grows the chip open, with rolling counts and clear"
  },
  {
    "slug": "color-swatches",
    "name": "Color Swatches",
    "category": "selection",
    "description": "Swatch radio group with a ring that grows out and a contrast-aware check"
  },
  {
    "slug": "radio-card",
    "name": "Radio Cards",
    "category": "selection",
    "description": "Plan-style cards where one selection ring slides to whichever you choose"
  },
  {
    "slug": "radio-group",
    "name": "Radio Group",
    "category": "selection",
    "description": "One choice from a few, with a dot that springs in and arrow-key roving"
  },
  {
    "slug": "rating",
    "name": "Rating",
    "category": "selection",
    "description": "Star rating with hover preview, half steps, scrubbing and a pop on commit"
  },
  {
    "slug": "segmented-control",
    "name": "Segmented Control",
    "category": "selection",
    "description": "One pill that springs between segments, with radio semantics and arrow keys"
  },
  {
    "slug": "switch",
    "name": "Switch",
    "category": "selection",
    "description": "Sprung thumb that stretches while held, and waits on async saves in place"
  },
  {
    "slug": "thumbs-feedback",
    "name": "Thumbs Feedback",
    "category": "selection",
    "description": "Helpful or not, with reasons on a thumbs down and a drawn thanks"
  },
  {
    "slug": "detent-slider",
    "name": "Detent Slider",
    "category": "sliders",
    "description": "Named stops you can feel: resists near each one, springs into place"
  },
  {
    "slug": "dial",
    "name": "Dial",
    "category": "sliders",
    "description": "Rotary knob with drag, wheel and keys, a bipolar arc and rolling readout"
  },
  {
    "slug": "histogram-range",
    "name": "Histogram Range",
    "category": "sliders",
    "description": "Price filter whose bars light up exactly between the thumbs as they move"
  },
  {
    "slug": "media-scrubber",
    "name": "Media Scrubber",
    "category": "sliders",
    "description": "Seek bar with chapters, buffered ranges and a time tip that tracks the pointer"
  },
  {
    "slug": "range-slider",
    "name": "Range Slider",
    "category": "sliders",
    "description": "Two thumbs whose labels merge when close, synced with typed min and max"
  },
  {
    "slug": "slider",
    "name": "Slider",
    "category": "sliders",
    "description": "Thumb swells on grab, value rides above it, pressed track glides"
  },
  {
    "slug": "volume-control",
    "name": "Volume Control",
    "category": "sliders",
    "description": "Speaker waves follow the level; mute remembers, wheel nudges, popover tucks away"
  },
  {
    "slug": "zoom-control",
    "name": "Zoom Control",
    "category": "sliders",
    "description": "Minus, rolling percentage and plus, with a type-or-pick menu and pinch zoom"
  },
  {
    "slug": "async-combobox",
    "name": "Async Combobox",
    "category": "pickers",
    "description": "Remote search that debounces, aborts stale requests and never jolts the list"
  },
  {
    "slug": "cascader",
    "name": "Cascader",
    "category": "pickers",
    "description": "Nested columns that grow in beside each other, with search across every path"
  },
  {
    "slug": "color-picker",
    "name": "Color Picker",
    "category": "pickers",
    "description": "Drag, type or sample a color; hue survives grays and recents remember"
  },
  {
    "slug": "combobox",
    "name": "Combobox",
    "category": "pickers",
    "description": "Filters as you type, sets the matched run in bold and creates what’s missing"
  },
  {
    "slug": "emoji-picker",
    "name": "Emoji Picker",
    "category": "pickers",
    "description": "Search-first emoji grid with arrow keys, skin tones and categories that follow the scroll"
  },
  {
    "slug": "listbox",
    "name": "Listbox",
    "category": "pickers",
    "description": "An inline list where the choice slides between rows and picks merge into blocks"
  },
  {
    "slug": "multi-select",
    "name": "Multi Select",
    "category": "pickers",
    "description": "Chips that fit the field with a rolling +N, search, select all and clear"
  },
  {
    "slug": "phone-field",
    "name": "Phone Field",
    "category": "pickers",
    "description": "Formats as you type for the chosen country, and reads it from pasted numbers"
  },
  {
    "slug": "select",
    "name": "Select",
    "category": "pickers",
    "description": "Opens over its trigger with the choice aligned, and the new value slides in from where it was picked"
  },
  {
    "slug": "transfer-list",
    "name": "Transfer List",
    "category": "pickers",
    "description": "Two filterable lists where checked rows fly across and land highlighted"
  },
  {
    "slug": "calendar",
    "name": "Calendar",
    "category": "dates",
    "description": "Locale-true month grid that slides the way you travel and sweeps ranges in"
  },
  {
    "slug": "countdown",
    "name": "Countdown",
    "category": "dates",
    "description": "Rolling-digit countdown that sleeps off screen and lands in an ended state"
  },
  {
    "slug": "date-field",
    "name": "Date Field",
    "category": "dates",
    "description": "Typed date in the locale's order, with stepping digits and plain-word errors"
  },
  {
    "slug": "date-picker",
    "name": "Date Picker",
    "category": "dates",
    "description": "Type “next fri” or pick from the calendar; it reads back before committing"
  },
  {
    "slug": "date-range-picker",
    "name": "Date Range Picker",
    "category": "dates",
    "description": "Two months, presets that sweep the range in, and a draft until Apply"
  },
  {
    "slug": "relative-time",
    "name": "Relative Time",
    "category": "dates",
    "description": "“3 minutes ago” that wakes only when its words change, digits rolling"
  },
  {
    "slug": "time-picker",
    "name": "Time Picker",
    "category": "dates",
    "description": "Segmented time field in the locale's order, with rolling digits and a slot list"
  },
  {
    "slug": "week-strip",
    "name": "Week Strip",
    "category": "dates",
    "description": "Phone-style day selector with a sprung pill, swipeable weeks and event dots"
  },
  {
    "slug": "agenda",
    "name": "Agenda",
    "category": "scheduling",
    "description": "Upcoming events by day with a Now line and a Join that counts down"
  },
  {
    "slug": "availability-editor",
    "name": "Availability Editor",
    "category": "scheduling",
    "description": "Weekly hours with split shifts, copy to other days and overlap checks"
  },
  {
    "slug": "booking-slots",
    "name": "Booking Slots",
    "category": "scheduling",
    "description": "Pick a day, then a time that splits in place to reveal Confirm"
  },
  {
    "slug": "event-calendar",
    "name": "Event Calendar",
    "category": "scheduling",
    "description": "Month view that packs multi-day bars and chips into lanes, overflowing into a day list"
  },
  {
    "slug": "timezone-select",
    "name": "Timezone Select",
    "category": "scheduling",
    "description": "Every IANA zone with live local time, searchable by city, name or offset"
  },
  {
    "slug": "week-grid",
    "name": "Week Grid",
    "category": "scheduling",
    "description": "Time grid where overlaps sit side by side and you drag to create, move or resize"
  },
  {
    "slug": "autosave-status",
    "name": "Autosave Status",
    "category": "forms",
    "description": "Saving, saved, offline and failed states in one pill that springs to fit"
  },
  {
    "slug": "avatar-upload",
    "name": "Avatar Upload",
    "category": "forms",
    "description": "Pick, crop and zoom a photo, then watch a ring close around it"
  },
  {
    "slug": "char-limit-ring",
    "name": "Character Limit Ring",
    "category": "forms",
    "description": "A tiny ring that fills as you type, then counts down and over"
  },
  {
    "slug": "dropzone",
    "name": "Dropzone",
    "category": "forms",
    "description": "Lights up when files cross the window, seals its dashes, names every rejection"
  },
  {
    "slug": "error-summary",
    "name": "Error Summary",
    "category": "forms",
    "description": "Lists every problem on submit, links to each field, and thins out as you fix"
  },
  {
    "slug": "field",
    "name": "Field",
    "category": "forms",
    "description": "Label, control, hint and error that speak up on blur, not on every keystroke"
  },
  {
    "slug": "inline-validation",
    "name": "Inline Validation",
    "category": "forms",
    "description": "Async checks that spin, then draw a tick or strike a cross, without flicker"
  },
  {
    "slug": "multi-step-form",
    "name": "Multi-step Form",
    "category": "forms",
    "description": "Steps slide the way you travel, validate one at a time, and keep every answer"
  },
  {
    "slug": "save-bar",
    "name": "Save Bar",
    "category": "forms",
    "description": "Rises when a form is dirty, nudges before you leave, ticks once saved"
  },
  {
    "slug": "signature-pad",
    "name": "Signature Pad",
    "category": "forms",
    "description": "Smooth, speed-weighted ink with undo, a typed alternative and trimmed PNG/SVG export"
  },
  {
    "slug": "upload-list",
    "name": "Upload List",
    "category": "forms",
    "description": "Per-file progress with smoothed speed and time left, retry, and a tick on finish"
  },
  {
    "slug": "empty-state",
    "name": "Empty State",
    "category": "async",
    "description": "One line, one reason, one action, with an icon that draws itself in"
  },
  {
    "slug": "error-state",
    "name": "Error State",
    "category": "async",
    "description": "Says what failed and what to do, retries in place, counts every attempt"
  },
  {
    "slug": "infinite-list",
    "name": "Infinite List",
    "category": "async",
    "description": "A scrolling feed that prefetches pages under skeletons and recovers from failures"
  },
  {
    "slug": "load-more",
    "name": "Load More",
    "category": "async",
    "description": "Appends the next page with a stagger, moves focus and never jumps"
  },
  {
    "slug": "progress-bar",
    "name": "Progress Bar",
    "category": "async",
    "description": "Rolling percentage, buffer, stepped segments and a tick that draws on completion"
  },
  {
    "slug": "progress-ring",
    "name": "Progress Ring",
    "category": "async",
    "description": "Circular progress with a rolling percentage that closes into a drawn tick"
  },
  {
    "slug": "pull-to-refresh",
    "name": "Pull to Refresh",
    "category": "async",
    "description": "Rubber-band pull with a filling ring, a flipping arrow and a sprung return"
  },
  {
    "slug": "skeleton",
    "name": "Skeleton",
    "category": "async",
    "description": "Bones sized to your text’s line box, lit by one shared slow sweep"
  },
  {
    "slug": "skeleton-swap",
    "name": "Skeleton Swap",
    "category": "async",
    "description": "Skeleton to content with a 4px settle and clearing blur, never a flash"
  },
  {
    "slug": "spinner",
    "name": "Spinner",
    "category": "async",
    "description": "Arc, dots and pixel-grid spinners drawn on the icon grid, so they swap for icons"
  },
  {
    "slug": "task-steps",
    "name": "Task Steps",
    "category": "async",
    "description": "Stages of a long job with live timers, drawn checks and a filling rail"
  },
  {
    "slug": "top-loader",
    "name": "Top Loader",
    "category": "async",
    "description": "A thin page bar that trickles, finishes fast and fades; skips fast loads"
  },
  {
    "slug": "announcement-bar",
    "name": "Announcement Bar",
    "category": "notifications",
    "description": "Slim top bar that rotates messages, holds while read and can be paused"
  },
  {
    "slug": "banner",
    "name": "Banner",
    "category": "notifications",
    "description": "Region-wide notice that collapses smoothly when dismissed and can remember it"
  },
  {
    "slug": "callout",
    "name": "Callout",
    "category": "notifications",
    "description": "Inline note, tip, warning or danger block with details that unfold in place"
  },
  {
    "slug": "connection-status",
    "name": "Connection Status",
    "category": "notifications",
    "description": "Offline, reconnecting and back-online in one pill that morphs between them"
  },
  {
    "slug": "cookie-consent",
    "name": "Cookie Consent",
    "category": "notifications",
    "description": "Compact consent card with equal choices and categories that unfold in place"
  },
  {
    "slug": "count-badge",
    "name": "Count Badge",
    "category": "notifications",
    "description": "A count that rolls its digits, pops when it rises and caps at 99+"
  },
  {
    "slug": "dynamic-island",
    "name": "Dynamic Island",
    "category": "notifications",
    "description": "A live-activity pill that springs open into controls and morphs between activities"
  },
  {
    "slug": "new-items-pill",
    "name": "New Items Pill",
    "category": "notifications",
    "description": "Holds new feed items behind a rolling count until the reader asks for them"
  },
  {
    "slug": "notification-inbox",
    "name": "Notification Inbox",
    "category": "notifications",
    "description": "A bell that rings on arrival and opens a grouped, keyboard-driven inbox with undo"
  },
  {
    "slug": "promise-toast",
    "name": "Promise Toast",
    "category": "notifications",
    "description": "One toast follows async work: spinner, live progress, then a tick drawn in place"
  },
  {
    "slug": "status-dot",
    "name": "Status Dot",
    "category": "notifications",
    "description": "Presence dot whose shape morphs between states, so color is never the only signal"
  },
  {
    "slug": "toast",
    "name": "Toast",
    "category": "notifications",
    "description": "Stacked toasts that fan out on hover, swipe away and update in place"
  },
  {
    "slug": "alert-dialog",
    "name": "Alert Dialog",
    "category": "dialogs",
    "description": "Destructive confirm that holds open while it works and explains failures in place"
  },
  {
    "slug": "bottom-sheet",
    "name": "Bottom Sheet",
    "category": "dialogs",
    "description": "Drag between peek, half and full; the list scrolls only once it's open"
  },
  {
    "slug": "dialog",
    "name": "Dialog",
    "category": "dialogs",
    "description": "Rises from .97 on the expo curve, scrolls inside with edge hairlines, nudges when refused"
  },
  {
    "slug": "hover-card",
    "name": "Hover Card",
    "category": "dialogs",
    "description": "Profile and link previews that prefetch on intent and draw the wait"
  },
  {
    "slug": "morph-dialog",
    "name": "Morph Dialog",
    "category": "dialogs",
    "description": "A card that opens into its dialog and folds back into the grid"
  },
  {
    "slug": "morph-popover",
    "name": "Morph Popover",
    "category": "dialogs",
    "description": "A button that grows into its own form and folds back into a tick"
  },
  {
    "slug": "popover",
    "name": "Popover",
    "category": "dialogs",
    "description": "Grows out of its trigger along a seamless arrow, flips at edges, opens on hover"
  },
  {
    "slug": "sheet",
    "name": "Sheet",
    "category": "dialogs",
    "description": "Side panel on the drawer curve that swipes away and resizes with give"
  },
  {
    "slug": "stacked-dialog",
    "name": "Stacked Dialog",
    "category": "dialogs",
    "description": "Each dialog opened from another pushes it back, dimmed, with a way back"
  },
  {
    "slug": "action-sheet",
    "name": "Action Sheet",
    "category": "menus",
    "description": "Rises from the bottom, swipes away, and holds for slow actions"
  },
  {
    "slug": "context-menu",
    "name": "Context Menu",
    "category": "menus",
    "description": "Opens at the pointer on right-click, long-press or Shift+F10"
  },
  {
    "slug": "dropdown-menu",
    "name": "Dropdown Menu",
    "category": "menus",
    "description": "Grows from its trigger, with one highlight that glides after the pointer"
  },
  {
    "slug": "menubar",
    "name": "Menubar",
    "category": "menus",
    "description": "File, Edit, View menus with one pill that slides between them"
  },
  {
    "slug": "overflow-menu",
    "name": "Overflow Menu",
    "category": "menus",
    "description": "Folds the least important controls into More as it narrows, by priority"
  },
  {
    "slug": "popconfirm",
    "name": "Popconfirm",
    "category": "menus",
    "description": "Asks where you pressed, starts on Cancel, and waits out async confirms"
  },
  {
    "slug": "row-actions",
    "name": "Row Actions",
    "category": "menus",
    "description": "Quick actions slide in over the row's meta, the rest wait in a menu"
  },
  {
    "slug": "selection-toolbar",
    "name": "Selection Toolbar",
    "category": "menus",
    "description": "Rises over selected text, glides as it changes, and morphs into a link field"
  },
  {
    "slug": "tooltip",
    "name": "Tooltip",
    "category": "menus",
    "description": "Waits once, then answers neighbors instantly, or glides one tooltip along a toolbar"
  },
  {
    "slug": "active-filters",
    "name": "Active Filters",
    "category": "command",
    "description": "Applied filters as removable chips that close ranks, fold to +N and undo"
  },
  {
    "slug": "command-pages",
    "name": "Command Pages",
    "category": "command",
    "description": "Palette pages that slide in, land on the current choice and remember the way back"
  },
  {
    "slug": "command-palette",
    "name": "Command Palette",
    "category": "command",
    "description": "⌘K opens it on the same frame, ranks matches and runs async commands in place"
  },
  {
    "slug": "faceted-filter",
    "name": "Faceted Filter",
    "category": "command",
    "description": "A filter button whose searchable popover ticks values, counts roll, chips collapse to +N"
  },
  {
    "slug": "filter-builder",
    "name": "Filter Builder",
    "category": "command",
    "description": "Filters written as sentences, each word a dropdown, with an all-or-any switch"
  },
  {
    "slug": "highlight-match",
    "name": "Highlight Match",
    "category": "command",
    "description": "Marks what matched in search results, accent-blind, with fuzzy mode and snippets"
  },
  {
    "slug": "kbd",
    "name": "Kbd",
    "category": "command",
    "description": "Keys written for the reader's platform that press down with the real ones"
  },
  {
    "slug": "scoped-search",
    "name": "Scoped Search",
    "category": "command",
    "description": "A search field where from: and in: become tokens with value suggestions"
  },
  {
    "slug": "search-dialog",
    "name": "Search Dialog",
    "category": "command",
    "description": "Async search with filter counts that roll, a live preview and stale-safe loading"
  },
  {
    "slug": "shortcuts-sheet",
    "name": "Shortcuts Sheet",
    "category": "command",
    "description": "Press ? for every shortcut; press any shortcut and its row lights up"
  },
  {
    "slug": "animated-link",
    "name": "Animated Link",
    "category": "navigation",
    "description": "Inline link whose underline draws in, retracts ahead and rewinds when interrupted"
  },
  {
    "slug": "breadcrumbs",
    "name": "Breadcrumbs",
    "category": "navigation",
    "description": "A trail that folds its middle into a menu to fit its width"
  },
  {
    "slug": "page-dots",
    "name": "Page Dots",
    "category": "navigation",
    "description": "Carousel dots whose active pill stretches, fills with autoplay time and scrolls when long"
  },
  {
    "slug": "pagination",
    "name": "Pagination",
    "category": "navigation",
    "description": "Numbered pages with a sliding pill, a rolling range and a steady width"
  },
  {
    "slug": "stepper",
    "name": "Stepper",
    "category": "navigation",
    "description": "Wizard steps whose numbers draw into ticks as the rail fills"
  },
  {
    "slug": "sub-nav",
    "name": "Sub Nav",
    "category": "navigation",
    "description": "Scrolling link strip with a gliding hover pill, edge fades and arrows"
  },
  {
    "slug": "tabs",
    "name": "Tabs",
    "category": "navigation",
    "description": "Sliding underline or pill, panels that crossfade and glide to height"
  },
  {
    "slug": "toc",
    "name": "Table of Contents",
    "category": "navigation",
    "description": "Scroll-spy contents whose rail steps with nesting and fills as you read"
  },
  {
    "slug": "tree-view",
    "name": "Tree View",
    "category": "navigation",
    "description": "A file tree that opens by height, lights its branch and types ahead"
  },
  {
    "slug": "vertical-tabs",
    "name": "Vertical Tabs",
    "category": "navigation",
    "description": "Settings-style side list with a gliding highlight that folds into a select"
  },
  {
    "slug": "icon-rail",
    "name": "Icon Rail",
    "category": "app-nav",
    "description": "Sidebar that folds to icons in place, with tooltips only when narrow"
  },
  {
    "slug": "mega-menu",
    "name": "Mega Menu",
    "category": "app-nav",
    "description": "Site menu with one panel that morphs between triggers and slides content"
  },
  {
    "slug": "mobile-menu",
    "name": "Mobile Menu",
    "category": "app-nav",
    "description": "Phone menu whose burger turns into the close, with sections that drill in"
  },
  {
    "slug": "navbar",
    "name": "Navbar",
    "category": "app-nav",
    "description": "Top bar that compacts on scroll while a pill follows the pointer home"
  },
  {
    "slug": "path-switcher",
    "name": "Path Switcher",
    "category": "app-nav",
    "description": "Team / project breadcrumb where every step is a searchable switcher that eases"
  },
  {
    "slug": "resizable-panels",
    "name": "Resizable Panels",
    "category": "app-nav",
    "description": "Split panes that drag, resist at their limits and spring shut on double-click"
  },
  {
    "slug": "sidebar",
    "name": "Sidebar",
    "category": "app-nav",
    "description": "App sidebar whose active pill springs between rows and whose counts roll"
  },
  {
    "slug": "tab-bar",
    "name": "Tab Bar",
    "category": "app-nav",
    "description": "Phone bottom navigation whose icons fill when active, with rolling badge counts"
  },
  {
    "slug": "user-menu",
    "name": "User Menu",
    "category": "app-nav",
    "description": "Avatar menu with presence, a sliding theme control and a sign-out that waits"
  },
  {
    "slug": "workspace-switcher",
    "name": "Workspace Switcher",
    "category": "app-nav",
    "description": "Searchable workspace menu with number shortcuts, pending switches and a rolling trigger"
  },
  {
    "slug": "accordion",
    "name": "Accordion",
    "category": "disclosure",
    "description": "Stacked sections that grow to fit, with answers find-in-page can still reach"
  },
  {
    "slug": "collapsible",
    "name": "Collapsible",
    "category": "disclosure",
    "description": "One section that folds away, plus a Show 3 more list that cascades in"
  },
  {
    "slug": "expandable-card",
    "name": "Expandable Card",
    "category": "disclosure",
    "description": "Cards that open in place to show details while the others make room"
  },
  {
    "slug": "interactive-card",
    "name": "Interactive Card",
    "category": "disclosure",
    "description": "The whole card is one link, while buttons inside still get their own clicks"
  },
  {
    "slug": "scroll-area",
    "name": "Scroll Area",
    "category": "disclosure",
    "description": "Native scrolling with thin overlay bars and edges that fade in as you scroll"
  },
  {
    "slug": "show-more",
    "name": "Show More",
    "category": "disclosure",
    "description": "Clamps long text with a fading last line, offering more only when it overflows"
  },
  {
    "slug": "back-to-top",
    "name": "Back to Top",
    "category": "scroll",
    "description": "Arrives after a screen, rings with progress, and hands focus back at the top"
  },
  {
    "slug": "hide-on-scroll",
    "name": "Hide on Scroll",
    "category": "scroll",
    "description": "Steps aside while you read down, returns on a deliberate scroll up"
  },
  {
    "slug": "overflow-scroller",
    "name": "Overflow Scroller",
    "category": "scroll",
    "description": "A horizontal row whose edge fades and arrows appear only where content hides"
  },
  {
    "slug": "reading-progress",
    "name": "Reading Progress",
    "category": "scroll",
    "description": "Tracks the article, not the page, and counts the minutes down"
  },
  {
    "slug": "scroll-reveal",
    "name": "Scroll Reveal",
    "category": "scroll",
    "description": "Reveals children once as they scroll in, with a capped stagger that never replays"
  },
  {
    "slug": "scroll-shadow",
    "name": "Scroll Shadow",
    "category": "scroll",
    "description": "Shades only the edges with more to scroll, tied to the scroll itself"
  },
  {
    "slug": "snap-carousel",
    "name": "Snap Carousel",
    "category": "scroll",
    "description": "Native scroll-snap carousel with sprung paging, mouse drag and dots that follow the scroll"
  },
  {
    "slug": "stacking-cards",
    "name": "Stacking Cards",
    "category": "scroll",
    "description": "Cards that stick and stack as you scroll, the ones behind shrinking and dimming"
  },
  {
    "slug": "sticky-header",
    "name": "Sticky Header",
    "category": "scroll",
    "description": "Invisible at rest, gains its edge and blur once content slides beneath"
  },
  {
    "slug": "virtual-list",
    "name": "Virtual List",
    "category": "scroll",
    "description": "A windowed listbox for 10,000 rows with measured heights and sticky group headers"
  },
  {
    "slug": "column-manager",
    "name": "Column Manager",
    "category": "tables",
    "description": "Show, hide and drag columns into order while the table rearranges live"
  },
  {
    "slug": "editable-cells",
    "name": "Editable Cells",
    "category": "tables",
    "description": "Spreadsheet cells that edit in place, validate per cell and flash when saved"
  },
  {
    "slug": "expandable-rows",
    "name": "Expandable Rows",
    "category": "tables",
    "description": "Rows open a detail panel that grows from beneath them and scrolls itself into view"
  },
  {
    "slug": "filter-grid",
    "name": "Filter Grid",
    "category": "tables",
    "description": "Card grid filtered by chips and search that reflows instead of reshuffling"
  },
  {
    "slug": "key-value-list",
    "name": "Key-Value List",
    "category": "tables",
    "description": "Details-panel pairs with copy, in-place edit and a wash that marks what changed"
  },
  {
    "slug": "row-selection",
    "name": "Row Selection",
    "category": "tables",
    "description": "Shift-click ranges that tick in sequence, and a bulk bar that rises with a rolling count"
  },
  {
    "slug": "sortable-table",
    "name": "Sortable Table",
    "category": "tables",
    "description": "Headers cycle through both directions and back, rows spring into their new order"
  },
  {
    "slug": "sticky-columns",
    "name": "Sticky Columns",
    "category": "tables",
    "description": "Pinned columns, header and totals whose edges shade only while something hides beneath"
  },
  {
    "slug": "table-pagination",
    "name": "Table Pagination",
    "category": "tables",
    "description": "Rows per page, rolling range, jump to page, and rows that crossfade the way you paged"
  },
  {
    "slug": "table-toolbar",
    "name": "Table Toolbar",
    "category": "tables",
    "description": "Search, filter, density, view and export in one arrow-key toolbar that reflows"
  },
  {
    "slug": "bar-chart",
    "name": "Bar Chart",
    "category": "data",
    "description": "Columns or ranked rows that grow in, morph on change and glide a tooltip"
  },
  {
    "slug": "contribution-graph",
    "name": "Contribution Graph",
    "category": "data",
    "description": "A year of daily activity as a keyboard-walkable heatmap with a gliding tooltip"
  },
  {
    "slug": "delta-badge",
    "name": "Delta Badge",
    "category": "data",
    "description": "Signed change with one arrow that turns, tinted by whether the change is good"
  },
  {
    "slug": "donut-chart",
    "name": "Donut Chart",
    "category": "data",
    "description": "A gapped ring that sweeps in, lifts a segment and rolls its value"
  },
  {
    "slug": "leaderboard",
    "name": "Leaderboard",
    "category": "data",
    "description": "Ranked rows that spring into place, roll their scores and pin you"
  },
  {
    "slug": "line-chart",
    "name": "Line Chart",
    "category": "data",
    "description": "Multi-series lines with a snapping crosshair, full readout and a toggling legend"
  },
  {
    "slug": "number-ticker",
    "name": "Number Ticker",
    "category": "data",
    "description": "Rolls each digit toward its new value in the direction it moved, tinting briefly"
  },
  {
    "slug": "poll-results",
    "name": "Poll Results",
    "category": "data",
    "description": "Tap to vote, then bars grow and counts roll up from zero"
  },
  {
    "slug": "sparkline",
    "name": "Sparkline",
    "category": "data",
    "description": "A tiny trend line that draws in once and scrubs to any point"
  },
  {
    "slug": "stat-tile",
    "name": "Stat Tile",
    "category": "data",
    "description": "KPI card whose sparkline you scrub to roll the headline to any day"
  },
  {
    "slug": "usage-meter",
    "name": "Usage Meter",
    "category": "data",
    "description": "Quota bar split by category that warns near the limit and shows overage honestly"
  },
  {
    "slug": "value-flash",
    "name": "Value Flash",
    "category": "data",
    "description": "Live value that washes green or red on each tick, throttled below three flashes a second"
  },
  {
    "slug": "avatar",
    "name": "Avatar",
    "category": "display",
    "description": "Photo that fades in once loaded, initials that never flash, presence that morphs"
  },
  {
    "slug": "avatar-group",
    "name": "Avatar Group",
    "category": "display",
    "description": "Overlapping faces with true cutouts that fan apart and open the full list"
  },
  {
    "slug": "badge",
    "name": "Badge",
    "category": "display",
    "description": "Status and count labels whose text, width and tone change in place"
  },
  {
    "slug": "entity-chip",
    "name": "Entity Chip",
    "category": "display",
    "description": "Inline mention of a person, repo or issue with a lazy-loading hover card"
  },
  {
    "slug": "heading-anchor",
    "name": "Heading Anchor",
    "category": "display",
    "description": "A heading whose # link copies the section URL, ticks and marks the section"
  },
  {
    "slug": "profile-card",
    "name": "Profile Card",
    "category": "display",
    "description": "A person with presence, local time and stats, and an optimistic follow that rolls back"
  },
  {
    "slug": "tag",
    "name": "Tag",
    "category": "display",
    "description": "Removable chips that fold away, close the gap and hand focus on"
  },
  {
    "slug": "timeline",
    "name": "Timeline",
    "category": "display",
    "description": "Activity grouped by day on a rail, where new events grow in at the top"
  },
  {
    "slug": "audio-player",
    "name": "Audio Player",
    "category": "media",
    "description": "Compact player whose waveform fills as it plays, with drag-to-seek and speed"
  },
  {
    "slug": "blur-up-image",
    "name": "Blur-up Image",
    "category": "media",
    "description": "Holds its space, then brings the full image into focus over a blurred preview"
  },
  {
    "slug": "file-thumbnail",
    "name": "File Thumbnail",
    "category": "media",
    "description": "File card by type that keeps the extension visible and shows upload progress"
  },
  {
    "slug": "gallery-grid",
    "name": "Gallery Grid",
    "category": "media",
    "description": "Masonry photos that blur up, select like a photo app and glide when rearranged"
  },
  {
    "slug": "image-compare",
    "name": "Image Compare",
    "category": "media",
    "description": "A before-and-after divider that follows a drag and springs to a click"
  },
  {
    "slug": "image-cropper",
    "name": "Image Cropper",
    "category": "media",
    "description": "Crop box with handles, aspect presets, zoom and rotate, exported to a Blob"
  },
  {
    "slug": "lightbox",
    "name": "Lightbox",
    "category": "media",
    "description": "Photos lift out of their thumbnails, swipe between, zoom, and land back where they came from"
  },
  {
    "slug": "product-gallery",
    "name": "Product Gallery",
    "category": "media",
    "description": "Product photos that crossfade on pick, swipe on touch and magnify under the mouse"
  },
  {
    "slug": "video-player",
    "name": "Video Player",
    "category": "media",
    "description": "Custom controls over native video, with chapters, subtitles and a morphing play button"
  },
  {
    "slug": "voice-recorder",
    "name": "Voice Recorder",
    "category": "media",
    "description": "Records with live input levels, pauses, and plays back before you send"
  },
  {
    "slug": "zoom-pan-image",
    "name": "Zoom Pan Image",
    "category": "media",
    "description": "Pinch, wheel or double-click to zoom where you point, then throw it around"
  },
  {
    "slug": "highlight",
    "name": "Highlight",
    "category": "content",
    "description": "A marker stroke drawn in reading order, carrying on across line breaks"
  },
  {
    "slug": "link-preview",
    "name": "Link Preview",
    "category": "content",
    "description": "Unfurled link card and inline hover preview sharing one cached request"
  },
  {
    "slug": "marquee",
    "name": "Marquee",
    "category": "content",
    "description": "Seamless infinite row that eases to a stop under the pointer"
  },
  {
    "slug": "prose",
    "name": "Prose",
    "category": "content",
    "description": "Token-only typography for rendered rich text, with section links and code copy"
  },
  {
    "slug": "spoiler",
    "name": "Spoiler",
    "category": "content",
    "description": "Grain-and-blur cover that dissolves outward from where you press it"
  },
  {
    "slug": "text-morph",
    "name": "Text Morph",
    "category": "content",
    "description": "Shared letters slide into their new places while the width springs"
  },
  {
    "slug": "text-reveal",
    "name": "Text Reveal",
    "category": "content",
    "description": "Words or wrapped lines lift out of a blur once, text left intact"
  },
  {
    "slug": "text-scramble",
    "name": "Text Scramble",
    "category": "content",
    "description": "Decodes left to right in fixed time, only where characters changed"
  },
  {
    "slug": "truncate",
    "name": "Truncate",
    "category": "content",
    "description": "Cuts text at the end or middle and unfolds it in place when cut"
  },
  {
    "slug": "drag-select",
    "name": "Drag Select",
    "category": "gestures",
    "description": "Rubber-band selection that scrolls at the edges and honors Shift and ⌘"
  },
  {
    "slug": "drop-target",
    "name": "Drop Target",
    "category": "gestures",
    "description": "Targets say what they take, pull the item in and send refusals home"
  },
  {
    "slug": "kanban",
    "name": "Kanban",
    "category": "gestures",
    "description": "Cards lean into the drag, land on an insertion line and move by menu too"
  },
  {
    "slug": "long-press",
    "name": "Long Press",
    "category": "gestures",
    "description": "Press and hold with a filling ring, right click and Shift F10 included"
  },
  {
    "slug": "pan-zoom-canvas",
    "name": "Pan Zoom Canvas",
    "category": "gestures",
    "description": "An infinite dot-grid canvas that pans, pinches and zooms to the cursor"
  },
  {
    "slug": "reorder-list",
    "name": "Reorder List",
    "category": "gestures",
    "description": "Lifts on press, springs neighbors aside and reorders from the keyboard too"
  },
  {
    "slug": "resizable-box",
    "name": "Resizable Box",
    "category": "gestures",
    "description": "Eight handles, a live size readout, Shift for ratio, Alt from center"
  },
  {
    "slug": "sortable-grid",
    "name": "Sortable Grid",
    "category": "gestures",
    "description": "Tiles lift off the grid, leave a slot behind and land where dropped"
  },
  {
    "slug": "swipe-actions",
    "name": "Swipe Actions",
    "category": "gestures",
    "description": "Swipe a row to reveal actions; swipe far and the tray fills to commit"
  },
  {
    "slug": "swipe-deck",
    "name": "Swipe Deck",
    "category": "gestures",
    "description": "A card stack you throw left or right, with undo and matching buttons"
  },
  {
    "slug": "activity-feed",
    "name": "Activity Feed",
    "category": "collaboration",
    "description": "A timeline of who did what, grouped by day, that holds your place as it updates"
  },
  {
    "slug": "comment-composer",
    "name": "Comment Composer",
    "category": "collaboration",
    "description": "Grows on focus, @mentions teammates, sends on ⌘↵ and keeps the draft"
  },
  {
    "slug": "comment-thread",
    "name": "Comment Thread",
    "category": "collaboration",
    "description": "Threaded comments that fold, resolve with a drawn tick and undo deletes"
  },
  {
    "slug": "follow-button",
    "name": "Follow Button",
    "category": "collaboration",
    "description": "Follow becomes Following with a drawn tick, offers Unfollow only when safe"
  },
  {
    "slug": "invite-field",
    "name": "Invite Field",
    "category": "collaboration",
    "description": "Turns typed or pasted addresses into chips, flags bad ones, sends with a role"
  },
  {
    "slug": "live-cursors",
    "name": "Live Cursors",
    "category": "collaboration",
    "description": "Teammates' pointers glide between network updates; idle names tuck into initials"
  },
  {
    "slug": "presence-stack",
    "name": "Presence Stack",
    "category": "collaboration",
    "description": "Live faces that slide in, ping once, fade out and roll the overflow count"
  },
  {
    "slug": "reaction-bar",
    "name": "Reaction Bar",
    "category": "collaboration",
    "description": "Emoji reactions that pop, roll their counts, say who, and roll back"
  },
  {
    "slug": "share-dialog",
    "name": "Share Dialog",
    "category": "collaboration",
    "description": "Invite by email, manage who has access and set link access in one place"
  },
  {
    "slug": "typing-indicator",
    "name": "Typing Indicator",
    "category": "collaboration",
    "description": "Who is typing, in words and a dot wave, opening its own height"
  },
  {
    "slug": "attachment-tray",
    "name": "Attachment Tray",
    "category": "messaging",
    "description": "Pending uploads that develop as they finish, retry in place and reorder"
  },
  {
    "slug": "chat-thread",
    "name": "Chat Thread",
    "category": "messaging",
    "description": "Grouped bubbles with tails, pinned to the latest while new messages rise in"
  },
  {
    "slug": "conversation-list",
    "name": "Conversation List",
    "category": "messaging",
    "description": "Chat inbox where rows spring to the top, counts roll and swipes commit"
  },
  {
    "slug": "jump-to-latest",
    "name": "Jump to Latest",
    "category": "messaging",
    "description": "Follows new messages at the bottom, then counts them when you scroll away"
  },
  {
    "slug": "message-composer",
    "name": "Message Composer",
    "category": "messaging",
    "description": "Grows with its text, takes files and emoji, and turns its mic into send"
  },
  {
    "slug": "message-status",
    "name": "Message Status",
    "category": "messaging",
    "description": "Delivery ticks that morph from clock to check to read, with a pressable retry"
  },
  {
    "slug": "reply-preview",
    "name": "Reply Preview",
    "category": "messaging",
    "description": "The quoted message slides up above the composer and jumps back to its original"
  },
  {
    "slug": "unread-divider",
    "name": "Unread Divider",
    "category": "messaging",
    "description": "New-messages line that draws out, counts up and folds away once read"
  },
  {
    "slug": "voice-message",
    "name": "Voice Message",
    "category": "messaging",
    "description": "A voice note whose waveform fills as it plays and seeks where you drag"
  },
  {
    "slug": "branch-switcher",
    "name": "Branch Switcher",
    "category": "ai-chat",
    "description": "Steps between regenerated replies; content slides the way you went, counts roll"
  },
  {
    "slug": "citations",
    "name": "Citations",
    "category": "ai-chat",
    "description": "Numbered source pills that preview on hover and light their list row"
  },
  {
    "slug": "context-meter",
    "name": "Context Meter",
    "category": "ai-chat",
    "description": "Ring or bar of context used, with a breakdown and a warning before full"
  },
  {
    "slug": "message-actions",
    "name": "Message Actions",
    "category": "ai-chat",
    "description": "The row under a reply: copy draws a tick, regenerate turns, thumbs fill"
  },
  {
    "slug": "model-picker",
    "name": "Model Picker",
    "category": "ai-chat",
    "description": "Compact model select with capabilities, speed and cost; the name slides and resizes"
  },
  {
    "slug": "prompt-input",
    "name": "Prompt Input",
    "category": "ai-chat",
    "description": "The AI composer: grows as you write, takes files, and Send becomes Stop"
  },
  {
    "slug": "reasoning",
    "name": "Reasoning",
    "category": "ai-chat",
    "description": "Thinking shown as one timed line that opens to the stream and folds itself away"
  },
  {
    "slug": "shimmer-text",
    "name": "Shimmer Text",
    "category": "ai-chat",
    "description": "A working status whose sheen sweeps the letters and crossfades between steps"
  },
  {
    "slug": "streaming-text",
    "name": "Streaming Text",
    "category": "ai-chat",
    "description": "A model's reply formatted as it streams, each chunk fading in, never flashing syntax"
  },
  {
    "slug": "suggestions",
    "name": "Suggestions",
    "category": "ai-chat",
    "description": "Prompt starters that stagger in once and fill the composer when picked"
  },
  {
    "slug": "agent-plan",
    "name": "Agent Plan",
    "category": "ai-agents",
    "description": "A live checklist the agent rewrites mid-run, with edits that grow in place"
  },
  {
    "slug": "agent-status",
    "name": "Agent Status",
    "category": "ai-agents",
    "description": "A live pill for a background agent that opens into its run and ends on a tick"
  },
  {
    "slug": "approval-card",
    "name": "Approval Card",
    "category": "ai-agents",
    "description": "An inline permission request that answers to Enter and Escape, then folds to one line"
  },
  {
    "slug": "diff-review",
    "name": "Diff Review",
    "category": "ai-agents",
    "description": "Accept or reject an agent's edits hunk by hunk; decided hunks fold into a tick"
  },
  {
    "slug": "generation-preview",
    "name": "Generation Preview",
    "category": "ai-agents",
    "description": "Generated images resolve from grain to sharp as progress climbs, then become choices"
  },
  {
    "slug": "response-feedback",
    "name": "Response Feedback",
    "category": "ai-agents",
    "description": "Thumbs that nod when pressed; a thumbs down unfolds reasons, a comment and send"
  },
  {
    "slug": "run-log",
    "name": "Run Log",
    "category": "ai-agents",
    "description": "A streaming log grouped by step that follows output until you scroll away"
  },
  {
    "slug": "tool-call",
    "name": "Tool Call",
    "category": "ai-agents",
    "description": "A tool invocation as one quiet row that opens into its JSON, live timer included"
  },
  {
    "slug": "voice-input",
    "name": "Voice Input",
    "category": "ai-agents",
    "description": "A mic that grows into a listening pill with live levels and words"
  },
  {
    "slug": "add-to-cart",
    "name": "Add to Cart",
    "category": "commerce",
    "description": "A button that morphs into a quantity stepper, with a cart badge that bumps"
  },
  {
    "slug": "card-field",
    "name": "Card Field",
    "category": "commerce",
    "description": "One card input that formats, detects the network, validates and advances itself"
  },
  {
    "slug": "cart-drawer",
    "name": "Cart Drawer",
    "category": "commerce",
    "description": "Slide-over cart whose lines collapse away and whose totals roll as you edit"
  },
  {
    "slug": "order-summary",
    "name": "Order Summary",
    "category": "commerce",
    "description": "Checkout totals that roll as they change and fold behind the total on phones"
  },
  {
    "slug": "plan-picker",
    "name": "Plan Picker",
    "category": "commerce",
    "description": "Plan radio cards that price the change, prorated, before anyone confirms it"
  },
  {
    "slug": "price-toggle",
    "name": "Price Toggle",
    "category": "commerce",
    "description": "Monthly or yearly switch whose savings badge swells the moment yearly is chosen"
  },
  {
    "slug": "pricing-table",
    "name": "Pricing Table",
    "category": "commerce",
    "description": "Plans side by side whose prices roll across the columns when the period changes"
  },
  {
    "slug": "promo-code",
    "name": "Promo Code",
    "category": "commerce",
    "description": "A code field that opens in place, checks quietly and lands as a chip"
  },
  {
    "slug": "quantity-stepper",
    "name": "Quantity Stepper",
    "category": "commerce",
    "description": "Rolls its digits, turns minus into remove at one and explains stock limits"
  },
  {
    "slug": "seat-picker",
    "name": "Seat Picker",
    "category": "commerce",
    "description": "Stepper and slider in sync, with a rolling total and volume tiers that light up"
  },
  {
    "slug": "trial-banner",
    "name": "Trial Banner",
    "category": "commerce",
    "description": "Trial countdown with one cell per day that turns urgent in the final days"
  },
  {
    "slug": "upgrade-prompt",
    "name": "Upgrade Prompt",
    "category": "commerce",
    "description": "Inline paywall at a limit, with a padlock that lifts as you reach Upgrade"
  },
  {
    "slug": "hotspot",
    "name": "Hotspot",
    "category": "onboarding",
    "description": "A beacon on a new feature that explains itself and stays dismissed"
  },
  {
    "slug": "magic-link",
    "name": "Magic Link",
    "category": "onboarding",
    "description": "Check-your-email screen with inbox shortcuts, a backing-off resend and a folding envelope"
  },
  {
    "slug": "onboarding-checklist",
    "name": "Onboarding Checklist",
    "category": "onboarding",
    "description": "A get-started card that ticks, strikes through and opens the next task"
  },
  {
    "slug": "passkey-button",
    "name": "Passkey Button",
    "category": "onboarding",
    "description": "Passkey sign-in whose glyph scans while the device prompt is open, with calm fallbacks"
  },
  {
    "slug": "product-tour",
    "name": "Product Tour",
    "category": "onboarding",
    "description": "Coach marks whose spotlight travels between targets, with the card gliding alongside"
  },
  {
    "slug": "session-timeout",
    "name": "Session Timeout",
    "category": "onboarding",
    "description": "An idle sign-out warning whose countdown rolls down and drains to zero"
  },
  {
    "slug": "sign-in-flow",
    "name": "Sign-in Flow",
    "category": "onboarding",
    "description": "Email first, then a password or emailed code, in a card that glides between heights"
  },
  {
    "slug": "social-buttons",
    "name": "Social Buttons",
    "category": "onboarding",
    "description": "Provider sign-in buttons with a gliding Last used badge and per-button loading"
  },
  {
    "slug": "two-factor-setup",
    "name": "Two-factor Setup",
    "category": "onboarding",
    "description": "Scan, verify and save recovery codes in one card that glides between steps"
  },
  {
    "slug": "whats-new",
    "name": "What's New",
    "category": "onboarding",
    "description": "A changelog popover with a rolling unread count and pages you step through"
  },
  {
    "slug": "api-key",
    "name": "API Key",
    "category": "settings",
    "description": "Masked secret that scrambles into view, copies, and regenerates behind a confirm"
  },
  {
    "slug": "locale-select",
    "name": "Locale Select",
    "category": "settings",
    "description": "Searchable language and region picker that previews dates and numbers before you choose"
  },
  {
    "slug": "member-list",
    "name": "Member List",
    "category": "settings",
    "description": "Team members and invites with rolling roles, confirmed removal and highlighted search"
  },
  {
    "slug": "notification-matrix",
    "name": "Notification Matrix",
    "category": "settings",
    "description": "Events by channels, column select-alls that ripple, and chip cards on phones"
  },
  {
    "slug": "session-list",
    "name": "Session List",
    "category": "settings",
    "description": "Signed-in devices that fold away on sign-out, one or all at once"
  },
  {
    "slug": "settings-row",
    "name": "Settings Row",
    "category": "settings",
    "description": "Label, description and control per row, each showing its own save as it happens"
  },
  {
    "slug": "shortcut-recorder",
    "name": "Shortcut Recorder",
    "category": "settings",
    "description": "Records a key combo live, sinks held keys and asks before stealing one"
  },
  {
    "slug": "theme-picker",
    "name": "Theme Picker",
    "category": "settings",
    "description": "Light, dark and system cards drawn in the real palettes, with a sliding ring"
  },
  {
    "slug": "type-to-confirm",
    "name": "Type to Confirm",
    "category": "settings",
    "description": "Type the exact name to unlock a destructive action; the padlock opens on match"
  },
  {
    "slug": "code-block",
    "name": "Code Block",
    "category": "developer",
    "description": "Highlighted code with a sticky gutter, wrap that hangs its indent, and folding"
  },
  {
    "slug": "code-tabs",
    "name": "Code Tabs",
    "category": "developer",
    "description": "Package manager or language tabs that remember the choice across every block"
  },
  {
    "slug": "deploy-status",
    "name": "Deploy Status",
    "category": "developer",
    "description": "Deployment row with a live, rolling duration and status changes that settle in place"
  },
  {
    "slug": "diff-viewer",
    "name": "Diff Viewer",
    "category": "developer",
    "description": "Unified or split diffs with word-level marks and folds that open in steps"
  },
  {
    "slug": "env-editor",
    "name": "Env Editor",
    "category": "developer",
    "description": "Environment variable rows with masked values, paste-a-.env import and duplicate warnings"
  },
  {
    "slug": "install-command",
    "name": "Install Command",
    "category": "developer",
    "description": "A one-line command whose verb swaps per package manager while the package slides"
  },
  {
    "slug": "json-viewer",
    "name": "JSON Viewer",
    "category": "developer",
    "description": "Folding JSON tree with search that unfolds to every match, and copyable paths"
  },
  {
    "slug": "log-viewer",
    "name": "Log Viewer",
    "category": "developer",
    "description": "Streaming logs that follow the tail, pause when you scroll up, and count what you missed"
  },
  {
    "slug": "terminal",
    "name": "Terminal",
    "category": "developer",
    "description": "A session that types itself with human pacing, in space it already reserved"
  },
  {
    "slug": "uptime-bars",
    "name": "Uptime Bars",
    "category": "developer",
    "description": "Ninety days of status bars with a gliding per-day tooltip and incident detail"
  },
  {
    "slug": "announcement-pill",
    "name": "Announcement Pill",
    "category": "marketing",
    "description": "Link above a hero where a sheen crosses once and the chevron becomes an arrow"
  },
  {
    "slug": "changelog",
    "name": "Changelog",
    "category": "marketing",
    "description": "Releases on a timeline rail that lights the one you’re reading"
  },
  {
    "slug": "comparison-table",
    "name": "Comparison Table",
    "category": "marketing",
    "description": "Plans against features with a sticky header, a gliding row highlight and phone view"
  },
  {
    "slug": "feature-tabs",
    "name": "Feature Tabs",
    "category": "marketing",
    "description": "Feature tour whose rail fills per tab, freezing on hover, focus or scroll-away"
  },
  {
    "slug": "newsletter-form",
    "name": "Newsletter Form",
    "category": "marketing",
    "description": "Inline email signup whose button grows over the field into the confirmation"
  },
  {
    "slug": "stats-band",
    "name": "Stats Band",
    "category": "marketing",
    "description": "Headline numbers whose digits spin up once, in turn, when scrolled into view"
  },
  {
    "slug": "testimonial-wall",
    "name": "Testimonial Wall",
    "category": "marketing",
    "description": "Masonry of quotes drifting in opposite columns that ease to a stop under the pointer"
  },
  {
    "slug": "waitlist-form",
    "name": "Waitlist Form",
    "category": "marketing",
    "description": "Join a waitlist, watch your place roll in, then share a referral link"
  },
  {
    "slug": "animate-height",
    "name": "Animate Height",
    "category": "motion",
    "description": "Follows its content’s height on a spring, measured, interruptible, auto at rest"
  },
  {
    "slug": "blur-in",
    "name": "Blur In",
    "category": "motion",
    "description": "Reveals content with a fade, a small rise and a clearing blur, once"
  },
  {
    "slug": "flip-list",
    "name": "FLIP List",
    "category": "motion",
    "description": "Rows glide to their new place on sort and filter; leavers step out first"
  },
  {
    "slug": "icon-swap",
    "name": "Icon Swap",
    "category": "motion",
    "description": "Swaps icons in a fixed box with a blur, turn or roll that knows direction"
  },
  {
    "slug": "presence-swap",
    "name": "Presence Swap",
    "category": "motion",
    "description": "Swaps views the way you're going, follows their height and keeps focus"
  },
  {
    "slug": "press-depth",
    "name": "Press Depth",
    "category": "motion",
    "description": "Any surface sinks, drops a pixel and flattens its shadow, then springs back"
  },
  {
    "slug": "ripple",
    "name": "Ripple",
    "category": "motion",
    "description": "A press wave from the pointer, in the surface's own text color"
  },
  {
    "slug": "stagger-in",
    "name": "Stagger In",
    "category": "motion",
    "description": "Rows arrive in one capped wave the first time, never on filters"
  }
];
